sudo: false  # https://docs.travis-ci.com/user/ci-environment/
language: python
cache: pip
matrix:
  include:
    - python: 2.7
      dist: trusty
      sudo: false
      env: FLASK=0.10
    - python: 2.7
      dist: trusty
      sudo: false
      env: FLASK=0.12
    - python: 2.7
      dist: trusty
      sudo: false
      env: FLASK=1.0.2
    - python: 3.4
      dist: trusty
      sudo: false
      env: FLASK=0.10
    - python: 3.4
      dist: trusty
      sudo: false
      env: FLASK=0.12
    - python: 3.4
      dist: trusty
      sudo: false
      env: FLASK=1.0.2
    - python: 3.5
      dist: trusty
      sudo: false
      env: FLASK=0.10
    - python: 3.5
      dist: trusty
      sudo: false
      env: FLASK=0.12
    - python: 3.5
      dist: trusty
      sudo: false
      env: FLASK=1.0.2
    - python: 3.6
      dist: trusty
      sudo: false
      env: FLASK=0.10
    - python: 3.6
      dist: trusty
      sudo: false
      env: FLASK=0.12
    - python: 3.6
      dist: trusty
      sudo: false
      env: FLASK=1.0.2
    - python: 3.7
      dist: xenial
      sudo: true
      env: FLASK=0.10
    - python: 3.7
      dist: xenial
      sudo: true
      env: FLASK=0.12
    - python: 3.7
      dist: xenial
      sudo: true
      env: FLASK=1.0.2
    - python: pypy
      dist: trusty
      sudo: false
      env: FLASK=0.10
    - python: pypy
      dist: trusty
      sudo: false
      env: FLASK=0.12
    - python: pypy
      dist: trusty
      sudo: false
      env: FLASK=1.0.2
    - python: pypy3
      dist: trusty
      sudo: false
      env: FLASK=0.10
    - python: pypy3
      dist: trusty
      sudo: false
      env: FLASK=0.12
    - python: pypy3
      dist: trusty
      sudo: false
      env: FLASK=1.0.2

install:
  - pip install -q Flask==$FLASK
  - pip install coveralls
script: make ci
after_success: coveralls

notifications:
  email:
    on_success: never
    on_failure: change
